### ISSUE TITLE
Plan completes successfully for resources even if I use a made-up API key and namespace

### ISSUE THREAD

**Issue by scott-doyland-burrows** [cloudsmith-io/terraform-provider-cloudsmith#125]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.10.0
on linux_amd64
+ provider registry.terraform.io/cloudsmith-io/cloudsmith v0.0.56

### Affected Resource(s)
All resources as far as I can tell.

### Expected Behavior
Plan should fail.

### Actual Behavior
Plan succeeds.

### Steps to Reproduce
Create config like this - note the API key and namespace.  These are used exactly as shown, ie they are made up.

```
terraform {
  required_providers {
    cloudsmith = {
      source = "cloudsmith-io/cloudsmith"
    }
  }
}

provider "cloudsmith" {
  api_key = "made-up-apikey"
}

resource "cloudsmith_repository" "repositories" {
  namespace = "made-up-namespace"
  slug      = "test"
  name      = "test"
}
```

Run a plan.  It will be successful.  But it should fail due to authentication issues.
Obviously the apply fails.

### Important Factoids
This is not correct terraform behavior and is very confusing.

Terraform should not show a successful plan when it clearly cannot authenticate with Cloudsmith.

**Comment by nickxn** [comment]
Thanks for raising @scott-doyland-burrows ! We've opening a ticket to fix

**Comment by BartoszBlizniak** [comment]
Hey @scott-doyland-burrows - this will be part of the next release (v0.0.57)
