### ISSUE TITLE
What are the correct parameter strings?

### ISSUE THREAD

**Issue by cdhunt** [cloudsmith-io/terraform-provider-cloudsmith#13]
The variables `repository_type` and `storage_region` take strings, but I can't find documentation on the expected valid strings.

https://help.cloudsmith.io/reference#repos_create

**Comment by DavidS-cloud** [comment]
hi @cdhunt ,

`repository_type` can be `public`, `private` or `open_source` at the moment.

The values for `storage_region` can be found by calling into https://help.cloudsmith.io/reference/#storage-regions_list and are currently:
* default
* ie-dublin
* de-frankfurt
* ca-montreal
* us-norcal
* us-ohio
* us-oregon
* sg-singapore
* au-sydney

I'll see to the docs update too, you shouldn't have to go spelunking in the API for this.

**Comment by cdhunt** [comment]
FWIW: Validation returns the following: `Error: expected repository_type to be one of [Private Public], got private`

**Comment by paddycarey** [comment]
I believe these should be documented in the provider and API defs now on help.cloudsmith.io
