### ISSUE TITLE
Add ability to create and interact with upstream proxies

### ISSUE THREAD

**Issue by christophermaier** [cloudsmith-io/terraform-provider-cloudsmith#18]
In addition to being able to create a repository with the Terraform provider, it would also be very useful to be able to manage any upstream proxies for that repository.

This currently has to be done manually, which can become rather tedious if you have many upstreams to configure.

**Comment by JesseRhoads-PD** [comment]
Plus one on this from us... it would be great to have upstream configurations reflected in code.

**Comment by chrisimcevoy** [comment]
Hi Folks,

Pleased to tell you that this is available as of 0.0.26, hot off the presses.

Here is a link to [the docs](https://github.com/cloudsmith-io/terraform-provider-cloudsmith/blob/master/docs/resources/repository_upstream.md) for convenience.
