### ISSUE TITLE
Drift on repository_type in cloudsmith_repository resource after upgrading provider 

### ISSUE THREAD

**Issue by pickgr** [cloudsmith-io/terraform-provider-cloudsmith#41]
### Terraform Version
```
Terraform v1.3.9
on darwin_amd64
+ provider registry.terraform.io/cloudsmith-io/cloudsmith v0.0.19
.
.
.
```

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudsmith_repository

### Terraform Configuration Files
```hcl
resource "cloudsmith_repository" "internal" {
  description     = "Repository that hosts Foo packages suitable for internal delivery."
  name            = "Internal"
  namespace       = data.cloudsmith_organization.this.slug_perm
  repository_type = "Private"
  slug            = "internal"
  storage_region  = "us-ohio" # https://github.com/cloudsmith-io/terraform-provider-cloudsmith/issues/13
}
```

### Debug Output

```
  # module.cicd.module.foo-cloudsmith.cloudsmith_repository.internal will be updated in-place
  ~ resource "cloudsmith_repository" "internal" {
        id                                   = "<redacted>"
        name                                 = "Internal"
      ~ repository_type                      = "private" -> "Private"
        # (43 unchanged attributes hidden)
    }
```

### Expected Behavior

No drift. ie:

```
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

### Actual Behavior
See debug output above

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Work-around

For now, I've added 

https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes

```
resource "cloudsmith_repository" "internal" {
  description     = "Repository that hosts Foo packages suitable for internal delivery."
  name            = "Internal"
  namespace       = data.cloudsmith_organization.this.slug_perm
  repository_type = "Private"
  slug            = "internal"
  storage_region  = "us-ohio" # https://github.com/cloudsmith-io/terraform-provider-cloudsmith/issues/13

  lifecycle {
    ignore_changes = [repository_type]
  }
}

```

**Comment by paddycarey** [comment]
Hey @pickgr, thanks for the report! This is related to a recent change on our API to allow case-insensitve values for that (and a few other fields). The Terraform provider currently enforces the old case sensitivity, we'll get a fix out for this ASAP.

**Comment by paddycarey** [comment]
@pickgr apologies for the late reply, this issue should be resolved and you should be able to remove the `ignore_changes` declaration now without drift. Let me know if you're still seeing issues.

**Comment by pickgr** [comment]
> @pickgr apologies for the late reply, this issue should be resolved and you should be able to remove the `ignore_changes` declaration now without drift. Let me know if you're still seeing issues.

Thank you @paddycarey !

I can confirm that this is indeed resolved now.
