### ISSUE TITLE
Feature Request: cloudsmith_file

### ISSUE THREAD

**Issue by jake-perkins** [cloudsmith-io/terraform-provider-cloudsmith#45]
Greetings,

Looking for native support within the cloudsmith provider to pull down specific packages, this is available in the artifactory provider like such

data "artifactory_file" "my-file" {
   repository   = "repo-key"
   path         = "/path/to/the/artifact.zip"
   output_path  = "tmp/artifact.zip"
}

Having similar offering with the cloudsmith provider will provide better parity for migration and support use-cases such as deploying an AWS Lambda with the package source being pulled directly from cloudsmith repository.

**Comment by BartoszBlizniak** [comment]
This feature has now been released
