### ISSUE TITLE
Documentation example uses deprecated data source

### ISSUE THREAD

**Issue by glowack2** [cloudsmith-io/terraform-provider-cloudsmith#72]
The documentation `/docs/index.md` references:

```
data "cloudsmith_namespace" "my_namespace" {
    slug = "my-namespace"
}
```

but using that example results in a `Warning: Deprecated Resource` and `use cloudsmith_organization data source instead`.

**Comment by DanMcKinney** [comment]
Thanks for this Ed, we will get a docs ticket opened to get this updated!

**Comment by BartoszBlizniak** [comment]
Hey @glowack2 , thank you for opening the issue. We will be making a large overhaul of our terraform provider and fixing the warnings later this year. I will close this issue for now as we will release updated version of the terraform provider with some new endpoints. 

Thank you,
Bartosz
