### ISSUE TITLE
`cloudsmith_service` documentation incorrect, causes 404

### ISSUE THREAD

**Issue by 4x0v7** [cloudsmith-io/terraform-provider-cloudsmith#74]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
`Terraform v1.5.7`

### Affected Resource(s)
Please list the resources as a list, for example:
- cloudsmith_service

### Terraform Configuration Files
```hcl
resource "cloudsmith_service" "my_service" {
    name         = "My Service"
    organization = data.cloudsmith_organization.my_org.slug_perm
}
```

### Expected Behavior
The service should be created

### Actual Behavior
`Error: 404 Not Found  (Not found.)`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create a service following the documentation
2. observe the error

## Resolution
Use `slug` instead of  `slug_perm`. The `cloudsmith_service` resource is created successfully

### Important Factoids
`cloudsmith_repository_privileges` appears to function with both `slug` or `slug_perm`, which is somewhat confusing 

### References
N/A

**Comment by BartoszBlizniak** [comment]
Hey @tbirk-bhs - due to the API designs coming from the engineering team, this will be just a documentation update to use `slug` instead of `slug_perm` so the functionality will remain the same. Thanks @4x0v7 for reporting this, it will be addressed in the next version.

**Comment by BartoszBlizniak** [comment]
This has been fixed up in the latest update!
