### ISSUE TITLE
Cloudsmith Repository documentation for argument reference contains false information

### ISSUE THREAD

**Issue by noelgass** [cloudsmith-io/terraform-provider-cloudsmith#87]
The documentation for Version 0.0.42 is incorrect for the resource #[cloudsmith_repository](https://registry.terraform.io/providers/cloudsmith-io/cloudsmith/latest/docs/resources/repository).

The property [deleted_at](https://registry.terraform.io/providers/cloudsmith-io/cloudsmith/latest/docs/resources/repository#deleted_at) is not present in the resource itself. Should be provided in the attribute reference only.

**Comment by BartoszBlizniak** [comment]
Hey, @noelgass - thank you for reporting - sharp eye! I'm currently taking a look at the PR you commented on and will be making the change under that.

**Comment by BartoszBlizniak** [comment]
This is being addressed in: https://github.com/cloudsmith-io/terraform-provider-cloudsmith/pull/88
